#!/usr/bin/env python3
"""
AI-Assisted Log Message Improvement Script

This script uses Claude (Anthropic's AI) to automatically improve log messages
from a CSV file generated by the logrefactor tool.

Usage:
    pip install anthropic pandas
    export ANTHROPIC_API_KEY="your-api-key"
    python improve_logs.py input.csv output.csv
"""

import sys
import os
import pandas as pd
from anthropic import Anthropic

def improve_log_message(client, original_text, function_call, arguments):
    """
    Use Claude to improve a single log message.
    
    Args:
        client: Anthropic client instance
        original_text: The original log message (with quotes)
        function_call: The logging function used (e.g., log.Printf)
        arguments: Any format string arguments
    
    Returns:
        Improved log message (without quotes)
    """
    # Remove quotes from original text for the prompt
    clean_text = original_text.strip('"\'`')
    
    # Build context
    context = f"Function: {function_call}"
    if arguments:
        context += f"\nArguments: {arguments}"
    
    prompt = f"""Improve this Go log message for clarity, professionalism, and consistency.

{context}
Original message: {clean_text}

Requirements:
- Use clear, professional language
- Be specific and actionable
- Use sentence case (capitalize first word only, except proper nouns)
- If this is a format string with %v, %s, %d, etc., keep those format verbs
- Return ONLY the improved message text, without quotes
- Keep it concise (under 100 characters if possible)

Improved message:"""

    try:
        message = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=300,
            messages=[{
                "role": "user",
                "content": prompt
            }]
        )
        
        # Extract the improved text
        improved = message.content[0].text.strip()
        
        # Remove any quotes that might have been added
        improved = improved.strip('"\'`')
        
        return improved
    
    except Exception as e:
        print(f"Error improving message: {e}")
        return None


def main():
    # Parse arguments
    if len(sys.argv) != 3:
        print("Usage: python improve_logs.py input.csv output.csv")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    # Check for API key
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("Error: ANTHROPIC_API_KEY environment variable not set")
        print("Set it with: export ANTHROPIC_API_KEY='your-api-key'")
        sys.exit(1)
    
    # Initialize Claude client
    print("Initializing Claude API client...")
    client = Anthropic(api_key=api_key)
    
    # Read CSV
    print(f"Reading {input_file}...")
    try:
        df = pd.read_csv(input_file)
    except Exception as e:
        print(f"Error reading CSV: {e}")
        sys.exit(1)
    
    # Validate CSV structure
    required_columns = ['ID', 'OriginalText', 'NewText', 'FunctionCall', 'Arguments']
    missing_columns = [col for col in required_columns if col not in df.columns]
    if missing_columns:
        print(f"Error: CSV missing required columns: {missing_columns}")
        sys.exit(1)
    
    # Process each row
    total = len(df)
    improved_count = 0
    skipped_count = 0
    
    print(f"\nProcessing {total} log entries...")
    print("-" * 80)
    
    for idx, row in df.iterrows():
        # Skip if already has NewText
        if pd.notna(row['NewText']) and row['NewText'] != '':
            skipped_count += 1
            continue
        
        # Get the original text
        original = row['OriginalText']
        if pd.isna(original) or original == '':
            skipped_count += 1
            continue
        
        print(f"\n[{idx + 1}/{total}] {row['ID']}")
        print(f"  Original: {original}")
        
        # Improve the message
        improved = improve_log_message(
            client,
            original,
            row['FunctionCall'],
            row['Arguments'] if pd.notna(row['Arguments']) else ''
        )
        
        if improved:
            df.at[idx, 'NewText'] = improved
            improved_count += 1
            print(f"  Improved: {improved}")
        else:
            print(f"  Failed to improve (keeping original)")
    
    print("\n" + "=" * 80)
    print(f"Summary:")
    print(f"  Total entries: {total}")
    print(f"  Improved: {improved_count}")
    print(f"  Skipped (already had NewText): {skipped_count}")
    print(f"  Failed: {total - improved_count - skipped_count}")
    
    # Save the updated CSV
    print(f"\nSaving to {output_file}...")
    try:
        df.to_csv(output_file, index=False)
        print(f"✓ Successfully saved to {output_file}")
    except Exception as e:
        print(f"Error saving CSV: {e}")
        sys.exit(1)
    
    print("\nNext steps:")
    print(f"1. Review {output_file} to verify the improvements")
    print(f"2. Run: ./logrefactor transform -input {output_file} -path ./your-project -dry-run")
    print(f"3. If satisfied, run: ./logrefactor transform -input {output_file} -path ./your-project")


if __name__ == "__main__":
    main()
